import DashbordHeader from "@/components/dashheader/DashbordHeader";
import "./globaldash.css";
import DashbordFooter from "@/components/dashbordfooter/DashbordFooter";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className=" flex flex-col min-h-screen">
        <DashbordHeader />
        {children}
        <DashbordFooter />
      </body>
    </html>
  );
}
